Repository Su24-CS5004-Online-Lionelle/final-project-group-3, pull requests merged in 2024-08, with the labels that each got.

#6 Feature model and cli
  build.gradle
  data/savedJobs.json
  gradlew
  src/main/java/jobplanner/JobBoardPlanner.java
  src/main/java/jobplanner/JobPlannerApp.java
  src/main/java/jobplanner/controller/ActionHandler.java
  src/main/java/jobplanner/controller/JobPlannerController.java
  src/main/java/jobplanner/model/Filters.java
  src/main/java/jobplanner/model/api/JobPostUtil.java
  src/main/java/jobplanner/model/formatters/DataFormatter.java
  src/main/java/jobplanner/model/models/IJobPostModel.java
  src/main/java/jobplanner/model/models/ISavedJobModel.java
  src/main/java/jobplanner/model/models/JobPostModel.java
  src/main/java/jobplanner/model/models/SavedJobModel.java
  src/main/java/jobplanner/model/types/JobCategory.java
  src/main/java/jobplanner/model/types/JobQueryParameter.java
  src/main/java/jobplanner/view/JobListPanel.java
  src/main/java/jobplanner/view/JobPlannerGUI.java
  src/main/java/jobplanner/view/JobTableModel.java
  src/main/java/jobplanner/view/SavedJobListPanel.java
Labels: documentation, enhancement

#7 Refactor model and add test cases for Model
  .idea/misc.xml
  src/main/java/jobplanner/controller/ActionHandler.java
  src/main/java/jobplanner/controller/InputValidator.java
  src/main/java/jobplanner/controller/JobPlannerController.java
  src/main/java/jobplanner/model/formatters/DataFormatter.java
  src/main/java/jobplanner/model/formatters/Formats.java
  src/main/java/jobplanner/model/models/ISavedJobModel.java
  src/main/java/jobplanner/model/models/SavedJobModel.java
  src/main/java/jobplanner/view/JobPlannerGUI.java
  src/main/java/jobplanner/view/SavedJobListPanel.java
  src/test/java/TestFilters.java
  src/test/java/TestJobPostModel.java
  src/test/java/TestSavedJobModel.java
Labels: enhancement

#8 Feature job search
  src/main/java/jobplanner/JobPlannerApp.java
  src/main/java/jobplanner/controller/ActionHandler.java
  src/main/java/jobplanner/controller/InputValidator.java
  src/main/java/jobplanner/controller/JobPlannerController.java
  src/main/java/jobplanner/model/api/JobPostUtil.java
  src/main/java/jobplanner/model/formatters/DataFormatter.java
  src/main/java/jobplanner/model/models/ISavedJobModel.java
  src/main/java/jobplanner/model/models/SavedJobModel.java
  src/main/java/jobplanner/model/types/JobCategory.java
  src/main/java/jobplanner/view/FilterPanel.java
  src/main/java/jobplanner/view/JobPlannerGUI.java
Labels: enhancement

#16 Store user saved jobs
  data/savedJobs.json
  src/main/java/jobplanner/controller/JobPlannerController.java
  src/main/java/jobplanner/view/JobTableModel.java
  src/test/java/TestSavedJobModel.java
Labels: enhancement

#24 Update docs and user manual
  Manual/README.md
  Manual/images/export-job-list.png
  Manual/images/main-screen-with-saved-list.png
  Manual/images/opening-screen.png
  Manual/images/saved-job-list-many.png
  Manual/images/saved-job-list.png
  src/main/java/jobplanner/controller/JobPlannerController.java
Labels: documentation

#25 Return more results from the API and save them
  data/jobpostings.json
  src/main/java/jobplanner/controller/JobPlannerController.java
  src/main/java/jobplanner/model/api/JobPostUtil.java
Labels: enhancement

#30 Unit Testing
  build.gradle
  src/main/java/jobplanner/JobPlannerApp.java
  src/main/java/jobplanner/controller/JobPlannerController.java
  src/main/java/jobplanner/model/Filters.java
  src/main/java/jobplanner/model/api/JobPostUtil.java
  src/main/java/jobplanner/model/types/JobQueryParameter.java
  src/main/java/jobplanner/view/tablemodels/JobTableModel.java
  src/main/java/jobplanner/view/tablemodels/SavedJobTableModel.java
  src/test/java/TestFilters.java
  src/test/java/TestInputValidator.java
  src/test/java/TestJobCategory.java
  src/test/java/TestJobPlannerController.java
  src/test/java/TestJobPostUtil.java
Labels: enhancement

#31 Design docs and final touches
  DesignDocuments/README.md
  DesignDocuments/final-gui-design-2.png
  DesignDocuments/final-gui-design.png
  DesignDocuments/initial-design-gui.png
  DesignDocuments/initial-design.png
  README.md
Labels: documentation
